// AUTO-GENERATED by scripts/sync-constants.cjs -- DO NOT EDIT.
// Source of truth: src/constants/bibleVersions.ts.
// Edit the frontend file and run: npm run sync-constants

// src/constants/bibleVersions.ts
// Making Disciples Daily -- SSOT: Bible Versions
//
// Owns the supported Bible versions and each version's fair-use length cap used
// by the scripture guardrail. v1 is manual paste only -- no public Bible API.
//
// RULE #11: Bible version IDs are LOWERCASE (kjv, esv, niv ...). The backend
// expects lowercase; normalizeVersionId() enforces this before any save.
//
// STUB STATE (Phase 0): the version list is empty until Lynn confirms the v1
// set; the lowercase-normalization rule is encoded now.

export type BibleVersionId = string;

export interface BibleVersion {
  id: BibleVersionId;     // lowercase, e.g. "kjv"
  label: string;          // display name, e.g. "King James Version"
  fairUseMaxChars: number;
}

export const BIBLE_VERSIONS: readonly BibleVersion[] = [];

// RULE #11: always normalize a version id to lowercase before saving.
export function normalizeVersionId(id: string): BibleVersionId {
  return id.trim().toLowerCase();
}
