// AUTO-GENERATED by scripts/sync-constants.cjs -- DO NOT EDIT.
// Source of truth: src/constants/routes.ts.
// Edit the frontend file and run: npm run sync-constants

// src/constants/routes.ts
// Making Disciples Daily -- SSOT: Routes
//
// Every route path is declared here ONCE. Components and the router import from
// this object -- never hardcode a path string elsewhere.
//
// RULE #3 (route bug pattern): every key added to ROUTES MUST also be wired into
// src/App.tsx in the SAME pass. The audit-ssot script verifies this.
//
// STUB STATE (Phase 0): only the landing route exists. Feature routes are added
// in their phase, each time updating App.tsx in the same commit.

export const ROUTES = {
  HOME: '/',
} as const;

export type RouteKey = keyof typeof ROUTES;
export type RoutePath = (typeof ROUTES)[RouteKey];
